repos:
-   repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
    -   id: autopep8

-   repo: https://github.com/pylint-dev/pylint
    rev: v3.2.7
    hooks:
    -   id: pylint 

-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.0
    hooks:
    -   id: bandit