name: Static Analysis

on:
  push:
    branches:
      - main
      - hw2badges
  pull_request:
    branches:
      - main
      - hw2badges

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.0-rc.1'
      - name: Install dependencies
        run: |
          pip install autopep8 pylint bandit
      - name: Run AutoPep8
        run: autopep8 --in-place --aggressive --recursive ..
      - name: Run Pylint
        run: |
          pylint $(find . -type f -name "*.py")
      - name: Run Bandit
        run: |
          bandit -r .
