name: Tests
run-name: ${{ github.actor }} is running tests.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13.0-rc.1"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.0-rc.1'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest test_fred.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
